### ISSUE TITLE
amp-sidebar

### ISSUE THREAD

**Issue by toshimaru** [toshimaru/blog.toshima.ru#20]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/amp-sidebar.md

**Comment by toshimaru** [comment]
```css

    amp-sidebar {
      width: 200px;
      padding: 0 20px;
    }
    amp-sidebar li {
      margin-bottom: 20px;
      list-style: none;
    }
```

```html
<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>

    <amp-sidebar id='sidebar1' layout='nodisplay'>
      <ul>
        <li>Nav item 1</li>
        <li> Nav item 2</li>
        <li> Nav item 3</li>
      </ul>
    </amp-sidebar>
    <button on='tap:sidebar1.toggle'>Toggle sidebar</button>
```
